// Code generated by Wire protocol buffer compiler, do not edit.
// Source: transit_realtime.Alert in xyz/ksharma/transport/gtfs_realtime.proto
@file:Suppress("DEPRECATION")

package xyz.ksharma.krail.model.gtfs_realtime.proto

import xyz.ksharma.krail.model.gtfs_realtime.proto.EntitySelector
import xyz.ksharma.krail.model.gtfs_realtime.proto.TimeRange
import xyz.ksharma.krail.model.gtfs_realtime.proto.TranslatedImage
import xyz.ksharma.krail.model.gtfs_realtime.proto.TranslatedString
import com.squareup.wire.EnumAdapter
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_2
import com.squareup.wire.WireEnum
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import com.squareup.wire.`internal`.JvmSynthetic
import com.squareup.wire.`internal`.checkElementsNotNull
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlin.Suppress
import kotlin.Unit
import kotlin.collections.List
import okio.ByteString

/**
 * An alert, indicating some sort of incident in the public transit network.
 */
public class Alert(
  active_period: List<TimeRange> = emptyList(),
  informed_entity: List<EntitySelector> = emptyList(),
  @field:WireField(
    tag = 6,
    adapter = "xyz.ksharma.krail.model.gtfs_realtime.proto.Alert${'$'}Cause#ADAPTER",
    schemaIndex = 2,
  )
  @JvmField
  public val cause: Cause? = null,
  @field:WireField(
    tag = 7,
    adapter = "xyz.ksharma.krail.model.gtfs_realtime.proto.Alert${'$'}Effect#ADAPTER",
    schemaIndex = 3,
  )
  @JvmField
  public val effect: Effect? = null,
  /**
   * The URL which provides additional information about the alert.
   */
  @field:WireField(
    tag = 8,
    adapter = "xyz.ksharma.krail.model.gtfs_realtime.proto.TranslatedString#ADAPTER",
    schemaIndex = 4,
  )
  @JvmField
  public val url: TranslatedString? = null,
  /**
   * Alert header. Contains a short summary of the alert text as plain-text.
   */
  @field:WireField(
    tag = 10,
    adapter = "xyz.ksharma.krail.model.gtfs_realtime.proto.TranslatedString#ADAPTER",
    schemaIndex = 5,
  )
  @JvmField
  public val header_text: TranslatedString? = null,
  /**
   * Full description for the alert as plain-text. The information in the
   * description should add to the information of the header.
   */
  @field:WireField(
    tag = 11,
    adapter = "xyz.ksharma.krail.model.gtfs_realtime.proto.TranslatedString#ADAPTER",
    schemaIndex = 6,
  )
  @JvmField
  public val description_text: TranslatedString? = null,
  /**
   * Text for alert header to be used in text-to-speech implementations. This field is the
   * text-to-speech version of header_text.
   */
  @field:WireField(
    tag = 12,
    adapter = "xyz.ksharma.krail.model.gtfs_realtime.proto.TranslatedString#ADAPTER",
    schemaIndex = 7,
  )
  @JvmField
  public val tts_header_text: TranslatedString? = null,
  /**
   * Text for full description for the alert to be used in text-to-speech implementations. This
   * field is the text-to-speech version of description_text.
   */
  @field:WireField(
    tag = 13,
    adapter = "xyz.ksharma.krail.model.gtfs_realtime.proto.TranslatedString#ADAPTER",
    schemaIndex = 8,
  )
  @JvmField
  public val tts_description_text: TranslatedString? = null,
  @field:WireField(
    tag = 14,
    adapter = "xyz.ksharma.krail.model.gtfs_realtime.proto.Alert${'$'}SeverityLevel#ADAPTER",
    schemaIndex = 9,
  )
  @JvmField
  public val severity_level: SeverityLevel? = null,
  /**
   * TranslatedImage to be displayed along the alert text. Used to explain visually the alert effect
   * of a detour, station closure, etc. The image must enhance the understanding of the alert. Any
   * essential information communicated within the image must also be contained in the alert text.
   * The following types of images are discouraged : image containing mainly text, marketing or
   * branded images that add no additional information.
   * NOTE: This field is still experimental, and subject to change. It may be formally adopted in
   * the future.
   */
  @field:WireField(
    tag = 15,
    adapter = "xyz.ksharma.krail.model.gtfs_realtime.proto.TranslatedImage#ADAPTER",
    schemaIndex = 10,
  )
  @JvmField
  public val image: TranslatedImage? = null,
  /**
   * Text describing the appearance of the linked image in the `image` field (e.g., in case the
   * image can't be displayed
   * or the user can't see the image for accessibility reasons). See the HTML spec for alt image
   * text - https://html.spec.whatwg.org/#alt.
   * NOTE: This field is still experimental, and subject to change. It may be formally adopted in
   * the future.
   */
  @field:WireField(
    tag = 16,
    adapter = "xyz.ksharma.krail.model.gtfs_realtime.proto.TranslatedString#ADAPTER",
    schemaIndex = 11,
  )
  @JvmField
  public val image_alternative_text: TranslatedString? = null,
  /**
   * Description of the cause of the alert that allows for agency-specific language; more specific
   * than the Cause. If cause_detail is included, then Cause must also be included.
   * NOTE: This field is still experimental, and subject to change. It may be formally adopted in
   * the future.
   */
  @field:WireField(
    tag = 17,
    adapter = "xyz.ksharma.krail.model.gtfs_realtime.proto.TranslatedString#ADAPTER",
    schemaIndex = 12,
  )
  @JvmField
  public val cause_detail: TranslatedString? = null,
  /**
   * Description of the effect of the alert that allows for agency-specific language; more specific
   * than the Effect. If effect_detail is included, then Effect must also be included.
   * NOTE: This field is still experimental, and subject to change. It may be formally adopted in
   * the future.
   */
  @field:WireField(
    tag = 18,
    adapter = "xyz.ksharma.krail.model.gtfs_realtime.proto.TranslatedString#ADAPTER",
    schemaIndex = 13,
  )
  @JvmField
  public val effect_detail: TranslatedString? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Alert, Alert.Builder>(ADAPTER, unknownFields) {
  /**
   * Time when the alert should be shown to the user. If missing, the
   * alert will be shown as long as it appears in the feed.
   * If multiple ranges are given, the alert will be shown during all of them.
   */
  @field:WireField(
    tag = 1,
    adapter = "xyz.ksharma.krail.model.gtfs_realtime.proto.TimeRange#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 0,
  )
  @JvmField
  public val active_period: List<TimeRange> = immutableCopyOf("active_period", active_period)

  /**
   * Entities whose users we should notify of this alert.
   */
  @field:WireField(
    tag = 5,
    adapter = "xyz.ksharma.krail.model.gtfs_realtime.proto.EntitySelector#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 1,
  )
  @JvmField
  public val informed_entity: List<EntitySelector> = immutableCopyOf("informed_entity",
      informed_entity)

  override fun newBuilder(): Builder {
    val builder = Builder()
    builder.active_period = active_period
    builder.informed_entity = informed_entity
    builder.cause = cause
    builder.effect = effect
    builder.url = url
    builder.header_text = header_text
    builder.description_text = description_text
    builder.tts_header_text = tts_header_text
    builder.tts_description_text = tts_description_text
    builder.severity_level = severity_level
    builder.image = image
    builder.image_alternative_text = image_alternative_text
    builder.cause_detail = cause_detail
    builder.effect_detail = effect_detail
    builder.addUnknownFields(unknownFields)
    return builder
  }

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Alert) return false
    if (unknownFields != other.unknownFields) return false
    if (active_period != other.active_period) return false
    if (informed_entity != other.informed_entity) return false
    if (cause != other.cause) return false
    if (effect != other.effect) return false
    if (url != other.url) return false
    if (header_text != other.header_text) return false
    if (description_text != other.description_text) return false
    if (tts_header_text != other.tts_header_text) return false
    if (tts_description_text != other.tts_description_text) return false
    if (severity_level != other.severity_level) return false
    if (image != other.image) return false
    if (image_alternative_text != other.image_alternative_text) return false
    if (cause_detail != other.cause_detail) return false
    if (effect_detail != other.effect_detail) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + active_period.hashCode()
      result = result * 37 + informed_entity.hashCode()
      result = result * 37 + (cause?.hashCode() ?: 0)
      result = result * 37 + (effect?.hashCode() ?: 0)
      result = result * 37 + (url?.hashCode() ?: 0)
      result = result * 37 + (header_text?.hashCode() ?: 0)
      result = result * 37 + (description_text?.hashCode() ?: 0)
      result = result * 37 + (tts_header_text?.hashCode() ?: 0)
      result = result * 37 + (tts_description_text?.hashCode() ?: 0)
      result = result * 37 + (severity_level?.hashCode() ?: 0)
      result = result * 37 + (image?.hashCode() ?: 0)
      result = result * 37 + (image_alternative_text?.hashCode() ?: 0)
      result = result * 37 + (cause_detail?.hashCode() ?: 0)
      result = result * 37 + (effect_detail?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (active_period.isNotEmpty()) result += """active_period=$active_period"""
    if (informed_entity.isNotEmpty()) result += """informed_entity=$informed_entity"""
    if (cause != null) result += """cause=$cause"""
    if (effect != null) result += """effect=$effect"""
    if (url != null) result += """url=$url"""
    if (header_text != null) result += """header_text=$header_text"""
    if (description_text != null) result += """description_text=$description_text"""
    if (tts_header_text != null) result += """tts_header_text=$tts_header_text"""
    if (tts_description_text != null) result += """tts_description_text=$tts_description_text"""
    if (severity_level != null) result += """severity_level=$severity_level"""
    if (image != null) result += """image=$image"""
    if (image_alternative_text != null) result +=
        """image_alternative_text=$image_alternative_text"""
    if (cause_detail != null) result += """cause_detail=$cause_detail"""
    if (effect_detail != null) result += """effect_detail=$effect_detail"""
    return result.joinToString(prefix = "Alert{", separator = ", ", postfix = "}")
  }

  public fun copy(
    active_period: List<TimeRange> = this.active_period,
    informed_entity: List<EntitySelector> = this.informed_entity,
    cause: Cause? = this.cause,
    effect: Effect? = this.effect,
    url: TranslatedString? = this.url,
    header_text: TranslatedString? = this.header_text,
    description_text: TranslatedString? = this.description_text,
    tts_header_text: TranslatedString? = this.tts_header_text,
    tts_description_text: TranslatedString? = this.tts_description_text,
    severity_level: SeverityLevel? = this.severity_level,
    image: TranslatedImage? = this.image,
    image_alternative_text: TranslatedString? = this.image_alternative_text,
    cause_detail: TranslatedString? = this.cause_detail,
    effect_detail: TranslatedString? = this.effect_detail,
    unknownFields: ByteString = this.unknownFields,
  ): Alert = Alert(active_period, informed_entity, cause, effect, url, header_text,
      description_text, tts_header_text, tts_description_text, severity_level, image,
      image_alternative_text, cause_detail, effect_detail, unknownFields)

  public class Builder : Message.Builder<Alert, Builder>() {
    @JvmField
    public var active_period: List<TimeRange> = emptyList()

    @JvmField
    public var informed_entity: List<EntitySelector> = emptyList()

    @JvmField
    public var cause: Cause? = null

    @JvmField
    public var effect: Effect? = null

    @JvmField
    public var url: TranslatedString? = null

    @JvmField
    public var header_text: TranslatedString? = null

    @JvmField
    public var description_text: TranslatedString? = null

    @JvmField
    public var tts_header_text: TranslatedString? = null

    @JvmField
    public var tts_description_text: TranslatedString? = null

    @JvmField
    public var severity_level: SeverityLevel? = null

    @JvmField
    public var image: TranslatedImage? = null

    @JvmField
    public var image_alternative_text: TranslatedString? = null

    @JvmField
    public var cause_detail: TranslatedString? = null

    @JvmField
    public var effect_detail: TranslatedString? = null

    /**
     * Time when the alert should be shown to the user. If missing, the
     * alert will be shown as long as it appears in the feed.
     * If multiple ranges are given, the alert will be shown during all of them.
     */
    public fun active_period(active_period: List<TimeRange>): Builder {
      checkElementsNotNull(active_period)
      this.active_period = active_period
      return this
    }

    /**
     * Entities whose users we should notify of this alert.
     */
    public fun informed_entity(informed_entity: List<EntitySelector>): Builder {
      checkElementsNotNull(informed_entity)
      this.informed_entity = informed_entity
      return this
    }

    public fun cause(cause: Cause?): Builder {
      this.cause = cause
      return this
    }

    public fun effect(effect: Effect?): Builder {
      this.effect = effect
      return this
    }

    /**
     * The URL which provides additional information about the alert.
     */
    public fun url(url: TranslatedString?): Builder {
      this.url = url
      return this
    }

    /**
     * Alert header. Contains a short summary of the alert text as plain-text.
     */
    public fun header_text(header_text: TranslatedString?): Builder {
      this.header_text = header_text
      return this
    }

    /**
     * Full description for the alert as plain-text. The information in the
     * description should add to the information of the header.
     */
    public fun description_text(description_text: TranslatedString?): Builder {
      this.description_text = description_text
      return this
    }

    /**
     * Text for alert header to be used in text-to-speech implementations. This field is the
     * text-to-speech version of header_text.
     */
    public fun tts_header_text(tts_header_text: TranslatedString?): Builder {
      this.tts_header_text = tts_header_text
      return this
    }

    /**
     * Text for full description for the alert to be used in text-to-speech implementations. This
     * field is the text-to-speech version of description_text.
     */
    public fun tts_description_text(tts_description_text: TranslatedString?): Builder {
      this.tts_description_text = tts_description_text
      return this
    }

    public fun severity_level(severity_level: SeverityLevel?): Builder {
      this.severity_level = severity_level
      return this
    }

    /**
     * TranslatedImage to be displayed along the alert text. Used to explain visually the alert
     * effect of a detour, station closure, etc. The image must enhance the understanding of the alert.
     * Any essential information communicated within the image must also be contained in the alert
     * text.
     * The following types of images are discouraged : image containing mainly text, marketing or
     * branded images that add no additional information.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in
     * the future.
     */
    public fun image(image: TranslatedImage?): Builder {
      this.image = image
      return this
    }

    /**
     * Text describing the appearance of the linked image in the `image` field (e.g., in case the
     * image can't be displayed
     * or the user can't see the image for accessibility reasons). See the HTML spec for alt image
     * text - https://html.spec.whatwg.org/#alt.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in
     * the future.
     */
    public fun image_alternative_text(image_alternative_text: TranslatedString?): Builder {
      this.image_alternative_text = image_alternative_text
      return this
    }

    /**
     * Description of the cause of the alert that allows for agency-specific language; more specific
     * than the Cause. If cause_detail is included, then Cause must also be included.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in
     * the future.
     */
    public fun cause_detail(cause_detail: TranslatedString?): Builder {
      this.cause_detail = cause_detail
      return this
    }

    /**
     * Description of the effect of the alert that allows for agency-specific language; more
     * specific than the Effect. If effect_detail is included, then Effect must also be included.
     * NOTE: This field is still experimental, and subject to change. It may be formally adopted in
     * the future.
     */
    public fun effect_detail(effect_detail: TranslatedString?): Builder {
      this.effect_detail = effect_detail
      return this
    }

    override fun build(): Alert = Alert(
      active_period = active_period,
      informed_entity = informed_entity,
      cause = cause,
      effect = effect,
      url = url,
      header_text = header_text,
      description_text = description_text,
      tts_header_text = tts_header_text,
      tts_description_text = tts_description_text,
      severity_level = severity_level,
      image = image,
      image_alternative_text = image_alternative_text,
      cause_detail = cause_detail,
      effect_detail = effect_detail,
      unknownFields = buildUnknownFields()
    )
  }

  public companion object {
    @JvmField
    public val DEFAULT_CAUSE: Cause = Cause.UNKNOWN_CAUSE

    @JvmField
    public val DEFAULT_EFFECT: Effect = Effect.UNKNOWN_EFFECT

    @JvmField
    public val DEFAULT_SEVERITY_LEVEL: SeverityLevel = SeverityLevel.UNKNOWN_SEVERITY

    @JvmField
    public val ADAPTER: ProtoAdapter<Alert> = object : ProtoAdapter<Alert>(
      FieldEncoding.LENGTH_DELIMITED, 
      Alert::class, 
      "type.googleapis.com/transit_realtime.Alert", 
      PROTO_2, 
      null, 
      "xyz/ksharma/transport/gtfs_realtime.proto"
    ) {
      override fun encodedSize(`value`: Alert): Int {
        var size = value.unknownFields.size
        size += TimeRange.ADAPTER.asRepeated().encodedSizeWithTag(1, value.active_period)
        size += EntitySelector.ADAPTER.asRepeated().encodedSizeWithTag(5, value.informed_entity)
        size += Cause.ADAPTER.encodedSizeWithTag(6, value.cause)
        size += Effect.ADAPTER.encodedSizeWithTag(7, value.effect)
        size += TranslatedString.ADAPTER.encodedSizeWithTag(8, value.url)
        size += TranslatedString.ADAPTER.encodedSizeWithTag(10, value.header_text)
        size += TranslatedString.ADAPTER.encodedSizeWithTag(11, value.description_text)
        size += TranslatedString.ADAPTER.encodedSizeWithTag(12, value.tts_header_text)
        size += TranslatedString.ADAPTER.encodedSizeWithTag(13, value.tts_description_text)
        size += SeverityLevel.ADAPTER.encodedSizeWithTag(14, value.severity_level)
        size += TranslatedImage.ADAPTER.encodedSizeWithTag(15, value.image)
        size += TranslatedString.ADAPTER.encodedSizeWithTag(16, value.image_alternative_text)
        size += TranslatedString.ADAPTER.encodedSizeWithTag(17, value.cause_detail)
        size += TranslatedString.ADAPTER.encodedSizeWithTag(18, value.effect_detail)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Alert) {
        TimeRange.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.active_period)
        EntitySelector.ADAPTER.asRepeated().encodeWithTag(writer, 5, value.informed_entity)
        Cause.ADAPTER.encodeWithTag(writer, 6, value.cause)
        Effect.ADAPTER.encodeWithTag(writer, 7, value.effect)
        TranslatedString.ADAPTER.encodeWithTag(writer, 8, value.url)
        TranslatedString.ADAPTER.encodeWithTag(writer, 10, value.header_text)
        TranslatedString.ADAPTER.encodeWithTag(writer, 11, value.description_text)
        TranslatedString.ADAPTER.encodeWithTag(writer, 12, value.tts_header_text)
        TranslatedString.ADAPTER.encodeWithTag(writer, 13, value.tts_description_text)
        SeverityLevel.ADAPTER.encodeWithTag(writer, 14, value.severity_level)
        TranslatedImage.ADAPTER.encodeWithTag(writer, 15, value.image)
        TranslatedString.ADAPTER.encodeWithTag(writer, 16, value.image_alternative_text)
        TranslatedString.ADAPTER.encodeWithTag(writer, 17, value.cause_detail)
        TranslatedString.ADAPTER.encodeWithTag(writer, 18, value.effect_detail)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Alert) {
        writer.writeBytes(value.unknownFields)
        TranslatedString.ADAPTER.encodeWithTag(writer, 18, value.effect_detail)
        TranslatedString.ADAPTER.encodeWithTag(writer, 17, value.cause_detail)
        TranslatedString.ADAPTER.encodeWithTag(writer, 16, value.image_alternative_text)
        TranslatedImage.ADAPTER.encodeWithTag(writer, 15, value.image)
        SeverityLevel.ADAPTER.encodeWithTag(writer, 14, value.severity_level)
        TranslatedString.ADAPTER.encodeWithTag(writer, 13, value.tts_description_text)
        TranslatedString.ADAPTER.encodeWithTag(writer, 12, value.tts_header_text)
        TranslatedString.ADAPTER.encodeWithTag(writer, 11, value.description_text)
        TranslatedString.ADAPTER.encodeWithTag(writer, 10, value.header_text)
        TranslatedString.ADAPTER.encodeWithTag(writer, 8, value.url)
        Effect.ADAPTER.encodeWithTag(writer, 7, value.effect)
        Cause.ADAPTER.encodeWithTag(writer, 6, value.cause)
        EntitySelector.ADAPTER.asRepeated().encodeWithTag(writer, 5, value.informed_entity)
        TimeRange.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.active_period)
      }

      override fun decode(reader: ProtoReader): Alert {
        val active_period = mutableListOf<TimeRange>()
        val informed_entity = mutableListOf<EntitySelector>()
        var cause: Cause? = null
        var effect: Effect? = null
        var url: TranslatedString? = null
        var header_text: TranslatedString? = null
        var description_text: TranslatedString? = null
        var tts_header_text: TranslatedString? = null
        var tts_description_text: TranslatedString? = null
        var severity_level: SeverityLevel? = null
        var image: TranslatedImage? = null
        var image_alternative_text: TranslatedString? = null
        var cause_detail: TranslatedString? = null
        var effect_detail: TranslatedString? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> active_period.add(TimeRange.ADAPTER.decode(reader))
            5 -> informed_entity.add(EntitySelector.ADAPTER.decode(reader))
            6 -> try {
              cause = Cause.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            7 -> try {
              effect = Effect.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            8 -> url = TranslatedString.ADAPTER.decode(reader)
            10 -> header_text = TranslatedString.ADAPTER.decode(reader)
            11 -> description_text = TranslatedString.ADAPTER.decode(reader)
            12 -> tts_header_text = TranslatedString.ADAPTER.decode(reader)
            13 -> tts_description_text = TranslatedString.ADAPTER.decode(reader)
            14 -> try {
              severity_level = SeverityLevel.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            15 -> image = TranslatedImage.ADAPTER.decode(reader)
            16 -> image_alternative_text = TranslatedString.ADAPTER.decode(reader)
            17 -> cause_detail = TranslatedString.ADAPTER.decode(reader)
            18 -> effect_detail = TranslatedString.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Alert(
          active_period = active_period,
          informed_entity = informed_entity,
          cause = cause,
          effect = effect,
          url = url,
          header_text = header_text,
          description_text = description_text,
          tts_header_text = tts_header_text,
          tts_description_text = tts_description_text,
          severity_level = severity_level,
          image = image,
          image_alternative_text = image_alternative_text,
          cause_detail = cause_detail,
          effect_detail = effect_detail,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Alert): Alert = value.copy(
        active_period = value.active_period.redactElements(TimeRange.ADAPTER),
        informed_entity = value.informed_entity.redactElements(EntitySelector.ADAPTER),
        url = value.url?.let(TranslatedString.ADAPTER::redact),
        header_text = value.header_text?.let(TranslatedString.ADAPTER::redact),
        description_text = value.description_text?.let(TranslatedString.ADAPTER::redact),
        tts_header_text = value.tts_header_text?.let(TranslatedString.ADAPTER::redact),
        tts_description_text = value.tts_description_text?.let(TranslatedString.ADAPTER::redact),
        image = value.image?.let(TranslatedImage.ADAPTER::redact),
        image_alternative_text =
            value.image_alternative_text?.let(TranslatedString.ADAPTER::redact),
        cause_detail = value.cause_detail?.let(TranslatedString.ADAPTER::redact),
        effect_detail = value.effect_detail?.let(TranslatedString.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L

    @JvmSynthetic
    public inline fun build(body: Builder.() -> Unit): Alert = Builder().apply(body).build()
  }

  /**
   * Cause of this alert. If cause_detail is included, then Cause must also be included.
   */
  public enum class Cause(
    override val `value`: Int,
  ) : WireEnum {
    UNKNOWN_CAUSE(1),
    /**
     * Not machine-representable.
     */
    OTHER_CAUSE(2),
    TECHNICAL_PROBLEM(3),
    /**
     * Public transit agency employees stopped working.
     */
    STRIKE(4),
    /**
     * People are blocking the streets.
     */
    DEMONSTRATION(5),
    ACCIDENT(6),
    HOLIDAY(7),
    WEATHER(8),
    MAINTENANCE(9),
    CONSTRUCTION(10),
    POLICE_ACTIVITY(11),
    MEDICAL_EMERGENCY(12),
    ;

    public companion object {
      @JvmField
      public val ADAPTER: ProtoAdapter<Cause> = object : EnumAdapter<Cause>(
        Cause::class, 
        PROTO_2, 
        null
      ) {
        override fun fromValue(`value`: Int): Cause? = Cause.fromValue(`value`)
      }

      @JvmStatic
      public fun fromValue(`value`: Int): Cause? = when (`value`) {
        1 -> UNKNOWN_CAUSE
        2 -> OTHER_CAUSE
        3 -> TECHNICAL_PROBLEM
        4 -> STRIKE
        5 -> DEMONSTRATION
        6 -> ACCIDENT
        7 -> HOLIDAY
        8 -> WEATHER
        9 -> MAINTENANCE
        10 -> CONSTRUCTION
        11 -> POLICE_ACTIVITY
        12 -> MEDICAL_EMERGENCY
        else -> null
      }
    }
  }

  /**
   * What is the effect of this problem on the affected entity. If effect_detail is included, then
   * Effect must also be included.
   */
  public enum class Effect(
    override val `value`: Int,
  ) : WireEnum {
    NO_SERVICE(1),
    REDUCED_SERVICE(2),
    /**
     * We don't care about INsignificant delays: they are hard to detect, have
     * little impact on the user, and would clutter the results as they are too
     * frequent.
     */
    SIGNIFICANT_DELAYS(3),
    DETOUR(4),
    ADDITIONAL_SERVICE(5),
    MODIFIED_SERVICE(6),
    OTHER_EFFECT(7),
    UNKNOWN_EFFECT(8),
    STOP_MOVED(9),
    NO_EFFECT(10),
    ACCESSIBILITY_ISSUE(11),
    ;

    public companion object {
      @JvmField
      public val ADAPTER: ProtoAdapter<Effect> = object : EnumAdapter<Effect>(
        Effect::class, 
        PROTO_2, 
        null
      ) {
        override fun fromValue(`value`: Int): Effect? = Effect.fromValue(`value`)
      }

      @JvmStatic
      public fun fromValue(`value`: Int): Effect? = when (`value`) {
        1 -> NO_SERVICE
        2 -> REDUCED_SERVICE
        3 -> SIGNIFICANT_DELAYS
        4 -> DETOUR
        5 -> ADDITIONAL_SERVICE
        6 -> MODIFIED_SERVICE
        7 -> OTHER_EFFECT
        8 -> UNKNOWN_EFFECT
        9 -> STOP_MOVED
        10 -> NO_EFFECT
        11 -> ACCESSIBILITY_ISSUE
        else -> null
      }
    }
  }

  /**
   * Severity of this alert.
   */
  public enum class SeverityLevel(
    override val `value`: Int,
  ) : WireEnum {
    UNKNOWN_SEVERITY(1),
    INFO(2),
    WARNING(3),
    SEVERE(4),
    ;

    public companion object {
      @JvmField
      public val ADAPTER: ProtoAdapter<SeverityLevel> = object : EnumAdapter<SeverityLevel>(
        SeverityLevel::class, 
        PROTO_2, 
        null
      ) {
        override fun fromValue(`value`: Int): SeverityLevel? = SeverityLevel.fromValue(`value`)
      }

      @JvmStatic
      public fun fromValue(`value`: Int): SeverityLevel? = when (`value`) {
        1 -> UNKNOWN_SEVERITY
        2 -> INFO
        3 -> WARNING
        4 -> SEVERE
        else -> null
      }
    }
  }
}
