// Code generated by Wire protocol buffer compiler, do not edit.
// Source: transit_realtime.StopSelector in xyz/ksharma/transport/gtfs_realtime.proto
@file:Suppress("DEPRECATION")

package xyz.ksharma.krail.model.gtfs_realtime.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_2
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmSynthetic
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlin.Suppress
import kotlin.Unit
import okio.ByteString

/**
 * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the
 * future.
 * Select a stop by stop sequence or by stop_id. At least one of the two values must be provided.
 */
public class StopSelector(
  /**
   * Must be the same as in stop_times.txt in the corresponding GTFS feed.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    schemaIndex = 0,
  )
  @JvmField
  public val stop_sequence: Int? = null,
  /**
   * Must be the same as in stops.txt in the corresponding GTFS feed.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 1,
  )
  @JvmField
  public val stop_id: String? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<StopSelector, StopSelector.Builder>(ADAPTER, unknownFields) {
  override fun newBuilder(): Builder {
    val builder = Builder()
    builder.stop_sequence = stop_sequence
    builder.stop_id = stop_id
    builder.addUnknownFields(unknownFields)
    return builder
  }

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is StopSelector) return false
    if (unknownFields != other.unknownFields) return false
    if (stop_sequence != other.stop_sequence) return false
    if (stop_id != other.stop_id) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (stop_sequence?.hashCode() ?: 0)
      result = result * 37 + (stop_id?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (stop_sequence != null) result += """stop_sequence=$stop_sequence"""
    if (stop_id != null) result += """stop_id=${sanitize(stop_id)}"""
    return result.joinToString(prefix = "StopSelector{", separator = ", ", postfix = "}")
  }

  public fun copy(
    stop_sequence: Int? = this.stop_sequence,
    stop_id: String? = this.stop_id,
    unknownFields: ByteString = this.unknownFields,
  ): StopSelector = StopSelector(stop_sequence, stop_id, unknownFields)

  public class Builder : Message.Builder<StopSelector, Builder>() {
    @JvmField
    public var stop_sequence: Int? = null

    @JvmField
    public var stop_id: String? = null

    /**
     * Must be the same as in stop_times.txt in the corresponding GTFS feed.
     */
    public fun stop_sequence(stop_sequence: Int?): Builder {
      this.stop_sequence = stop_sequence
      return this
    }

    /**
     * Must be the same as in stops.txt in the corresponding GTFS feed.
     */
    public fun stop_id(stop_id: String?): Builder {
      this.stop_id = stop_id
      return this
    }

    override fun build(): StopSelector = StopSelector(
      stop_sequence = stop_sequence,
      stop_id = stop_id,
      unknownFields = buildUnknownFields()
    )
  }

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<StopSelector> = object : ProtoAdapter<StopSelector>(
      FieldEncoding.LENGTH_DELIMITED, 
      StopSelector::class, 
      "type.googleapis.com/transit_realtime.StopSelector", 
      PROTO_2, 
      null, 
      "xyz/ksharma/transport/gtfs_realtime.proto"
    ) {
      override fun encodedSize(`value`: StopSelector): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.UINT32.encodedSizeWithTag(1, value.stop_sequence)
        size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.stop_id)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: StopSelector) {
        ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.stop_sequence)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.stop_id)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: StopSelector) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.encodeWithTag(writer, 2, value.stop_id)
        ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.stop_sequence)
      }

      override fun decode(reader: ProtoReader): StopSelector {
        var stop_sequence: Int? = null
        var stop_id: String? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> stop_sequence = ProtoAdapter.UINT32.decode(reader)
            2 -> stop_id = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return StopSelector(
          stop_sequence = stop_sequence,
          stop_id = stop_id,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: StopSelector): StopSelector = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L

    @JvmSynthetic
    public inline fun build(body: Builder.() -> Unit): StopSelector = Builder().apply(body).build()
  }
}
