// Code generated by Wire protocol buffer compiler, do not edit.
// Source: transit_realtime.Stop in xyz/ksharma/transport/gtfs_realtime.proto
@file:Suppress("DEPRECATION")

package xyz.ksharma.krail.model.gtfs_realtime.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_2
import com.squareup.wire.WireEnum
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import com.squareup.wire.`internal`.JvmSynthetic
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.Boolean
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlin.Suppress
import kotlin.Unit
import okio.ByteString

/**
 * Describes a stop which is served by trips. All fields are as described in the GTFS-Static
 * specification.
 * NOTE: This message is still experimental, and subject to change. It may be formally adopted in
 * the future.
 */
public class Stop(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 0,
  )
  @JvmField
  public val stop_id: String? = null,
  @field:WireField(
    tag = 2,
    adapter = "xyz.ksharma.krail.model.gtfs_realtime.proto.TranslatedString#ADAPTER",
    schemaIndex = 1,
  )
  @JvmField
  public val stop_code: TranslatedString? = null,
  @field:WireField(
    tag = 3,
    adapter = "xyz.ksharma.krail.model.gtfs_realtime.proto.TranslatedString#ADAPTER",
    schemaIndex = 2,
  )
  @JvmField
  public val stop_name: TranslatedString? = null,
  @field:WireField(
    tag = 4,
    adapter = "xyz.ksharma.krail.model.gtfs_realtime.proto.TranslatedString#ADAPTER",
    schemaIndex = 3,
  )
  @JvmField
  public val tts_stop_name: TranslatedString? = null,
  @field:WireField(
    tag = 5,
    adapter = "xyz.ksharma.krail.model.gtfs_realtime.proto.TranslatedString#ADAPTER",
    schemaIndex = 4,
  )
  @JvmField
  public val stop_desc: TranslatedString? = null,
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    schemaIndex = 5,
  )
  @JvmField
  public val stop_lat: Float? = null,
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    schemaIndex = 6,
  )
  @JvmField
  public val stop_lon: Float? = null,
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 7,
  )
  @JvmField
  public val zone_id: String? = null,
  @field:WireField(
    tag = 9,
    adapter = "xyz.ksharma.krail.model.gtfs_realtime.proto.TranslatedString#ADAPTER",
    schemaIndex = 8,
  )
  @JvmField
  public val stop_url: TranslatedString? = null,
  @field:WireField(
    tag = 11,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 9,
  )
  @JvmField
  public val parent_station: String? = null,
  @field:WireField(
    tag = 12,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 10,
  )
  @JvmField
  public val stop_timezone: String? = null,
  @field:WireField(
    tag = 13,
    adapter = "xyz.ksharma.krail.model.gtfs_realtime.proto.Stop${'$'}WheelchairBoarding#ADAPTER",
    schemaIndex = 11,
  )
  @JvmField
  public val wheelchair_boarding: WheelchairBoarding? = null,
  @field:WireField(
    tag = 14,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 12,
  )
  @JvmField
  public val level_id: String? = null,
  @field:WireField(
    tag = 15,
    adapter = "xyz.ksharma.krail.model.gtfs_realtime.proto.TranslatedString#ADAPTER",
    schemaIndex = 13,
  )
  @JvmField
  public val platform_code: TranslatedString? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Stop, Stop.Builder>(ADAPTER, unknownFields) {
  override fun newBuilder(): Builder {
    val builder = Builder()
    builder.stop_id = stop_id
    builder.stop_code = stop_code
    builder.stop_name = stop_name
    builder.tts_stop_name = tts_stop_name
    builder.stop_desc = stop_desc
    builder.stop_lat = stop_lat
    builder.stop_lon = stop_lon
    builder.zone_id = zone_id
    builder.stop_url = stop_url
    builder.parent_station = parent_station
    builder.stop_timezone = stop_timezone
    builder.wheelchair_boarding = wheelchair_boarding
    builder.level_id = level_id
    builder.platform_code = platform_code
    builder.addUnknownFields(unknownFields)
    return builder
  }

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Stop) return false
    if (unknownFields != other.unknownFields) return false
    if (stop_id != other.stop_id) return false
    if (stop_code != other.stop_code) return false
    if (stop_name != other.stop_name) return false
    if (tts_stop_name != other.tts_stop_name) return false
    if (stop_desc != other.stop_desc) return false
    if (stop_lat != other.stop_lat) return false
    if (stop_lon != other.stop_lon) return false
    if (zone_id != other.zone_id) return false
    if (stop_url != other.stop_url) return false
    if (parent_station != other.parent_station) return false
    if (stop_timezone != other.stop_timezone) return false
    if (wheelchair_boarding != other.wheelchair_boarding) return false
    if (level_id != other.level_id) return false
    if (platform_code != other.platform_code) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (stop_id?.hashCode() ?: 0)
      result = result * 37 + (stop_code?.hashCode() ?: 0)
      result = result * 37 + (stop_name?.hashCode() ?: 0)
      result = result * 37 + (tts_stop_name?.hashCode() ?: 0)
      result = result * 37 + (stop_desc?.hashCode() ?: 0)
      result = result * 37 + (stop_lat?.hashCode() ?: 0)
      result = result * 37 + (stop_lon?.hashCode() ?: 0)
      result = result * 37 + (zone_id?.hashCode() ?: 0)
      result = result * 37 + (stop_url?.hashCode() ?: 0)
      result = result * 37 + (parent_station?.hashCode() ?: 0)
      result = result * 37 + (stop_timezone?.hashCode() ?: 0)
      result = result * 37 + (wheelchair_boarding?.hashCode() ?: 0)
      result = result * 37 + (level_id?.hashCode() ?: 0)
      result = result * 37 + (platform_code?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (stop_id != null) result += """stop_id=${sanitize(stop_id)}"""
    if (stop_code != null) result += """stop_code=$stop_code"""
    if (stop_name != null) result += """stop_name=$stop_name"""
    if (tts_stop_name != null) result += """tts_stop_name=$tts_stop_name"""
    if (stop_desc != null) result += """stop_desc=$stop_desc"""
    if (stop_lat != null) result += """stop_lat=$stop_lat"""
    if (stop_lon != null) result += """stop_lon=$stop_lon"""
    if (zone_id != null) result += """zone_id=${sanitize(zone_id)}"""
    if (stop_url != null) result += """stop_url=$stop_url"""
    if (parent_station != null) result += """parent_station=${sanitize(parent_station)}"""
    if (stop_timezone != null) result += """stop_timezone=${sanitize(stop_timezone)}"""
    if (wheelchair_boarding != null) result += """wheelchair_boarding=$wheelchair_boarding"""
    if (level_id != null) result += """level_id=${sanitize(level_id)}"""
    if (platform_code != null) result += """platform_code=$platform_code"""
    return result.joinToString(prefix = "Stop{", separator = ", ", postfix = "}")
  }

  public fun copy(
    stop_id: String? = this.stop_id,
    stop_code: TranslatedString? = this.stop_code,
    stop_name: TranslatedString? = this.stop_name,
    tts_stop_name: TranslatedString? = this.tts_stop_name,
    stop_desc: TranslatedString? = this.stop_desc,
    stop_lat: Float? = this.stop_lat,
    stop_lon: Float? = this.stop_lon,
    zone_id: String? = this.zone_id,
    stop_url: TranslatedString? = this.stop_url,
    parent_station: String? = this.parent_station,
    stop_timezone: String? = this.stop_timezone,
    wheelchair_boarding: WheelchairBoarding? = this.wheelchair_boarding,
    level_id: String? = this.level_id,
    platform_code: TranslatedString? = this.platform_code,
    unknownFields: ByteString = this.unknownFields,
  ): Stop = Stop(stop_id, stop_code, stop_name, tts_stop_name, stop_desc, stop_lat, stop_lon,
      zone_id, stop_url, parent_station, stop_timezone, wheelchair_boarding, level_id,
      platform_code, unknownFields)

  public class Builder : Message.Builder<Stop, Builder>() {
    @JvmField
    public var stop_id: String? = null

    @JvmField
    public var stop_code: TranslatedString? = null

    @JvmField
    public var stop_name: TranslatedString? = null

    @JvmField
    public var tts_stop_name: TranslatedString? = null

    @JvmField
    public var stop_desc: TranslatedString? = null

    @JvmField
    public var stop_lat: Float? = null

    @JvmField
    public var stop_lon: Float? = null

    @JvmField
    public var zone_id: String? = null

    @JvmField
    public var stop_url: TranslatedString? = null

    @JvmField
    public var parent_station: String? = null

    @JvmField
    public var stop_timezone: String? = null

    @JvmField
    public var wheelchair_boarding: WheelchairBoarding? = null

    @JvmField
    public var level_id: String? = null

    @JvmField
    public var platform_code: TranslatedString? = null

    public fun stop_id(stop_id: String?): Builder {
      this.stop_id = stop_id
      return this
    }

    public fun stop_code(stop_code: TranslatedString?): Builder {
      this.stop_code = stop_code
      return this
    }

    public fun stop_name(stop_name: TranslatedString?): Builder {
      this.stop_name = stop_name
      return this
    }

    public fun tts_stop_name(tts_stop_name: TranslatedString?): Builder {
      this.tts_stop_name = tts_stop_name
      return this
    }

    public fun stop_desc(stop_desc: TranslatedString?): Builder {
      this.stop_desc = stop_desc
      return this
    }

    public fun stop_lat(stop_lat: Float?): Builder {
      this.stop_lat = stop_lat
      return this
    }

    public fun stop_lon(stop_lon: Float?): Builder {
      this.stop_lon = stop_lon
      return this
    }

    public fun zone_id(zone_id: String?): Builder {
      this.zone_id = zone_id
      return this
    }

    public fun stop_url(stop_url: TranslatedString?): Builder {
      this.stop_url = stop_url
      return this
    }

    public fun parent_station(parent_station: String?): Builder {
      this.parent_station = parent_station
      return this
    }

    public fun stop_timezone(stop_timezone: String?): Builder {
      this.stop_timezone = stop_timezone
      return this
    }

    public fun wheelchair_boarding(wheelchair_boarding: WheelchairBoarding?): Builder {
      this.wheelchair_boarding = wheelchair_boarding
      return this
    }

    public fun level_id(level_id: String?): Builder {
      this.level_id = level_id
      return this
    }

    public fun platform_code(platform_code: TranslatedString?): Builder {
      this.platform_code = platform_code
      return this
    }

    override fun build(): Stop = Stop(
      stop_id = stop_id,
      stop_code = stop_code,
      stop_name = stop_name,
      tts_stop_name = tts_stop_name,
      stop_desc = stop_desc,
      stop_lat = stop_lat,
      stop_lon = stop_lon,
      zone_id = zone_id,
      stop_url = stop_url,
      parent_station = parent_station,
      stop_timezone = stop_timezone,
      wheelchair_boarding = wheelchair_boarding,
      level_id = level_id,
      platform_code = platform_code,
      unknownFields = buildUnknownFields()
    )
  }

  public companion object {
    @JvmField
    public val DEFAULT_WHEELCHAIR_BOARDING: WheelchairBoarding = WheelchairBoarding.UNKNOWN

    @JvmField
    public val ADAPTER: ProtoAdapter<Stop> = object : ProtoAdapter<Stop>(
      FieldEncoding.LENGTH_DELIMITED, 
      Stop::class, 
      "type.googleapis.com/transit_realtime.Stop", 
      PROTO_2, 
      null, 
      "xyz/ksharma/transport/gtfs_realtime.proto"
    ) {
      override fun encodedSize(`value`: Stop): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.stop_id)
        size += TranslatedString.ADAPTER.encodedSizeWithTag(2, value.stop_code)
        size += TranslatedString.ADAPTER.encodedSizeWithTag(3, value.stop_name)
        size += TranslatedString.ADAPTER.encodedSizeWithTag(4, value.tts_stop_name)
        size += TranslatedString.ADAPTER.encodedSizeWithTag(5, value.stop_desc)
        size += ProtoAdapter.FLOAT.encodedSizeWithTag(6, value.stop_lat)
        size += ProtoAdapter.FLOAT.encodedSizeWithTag(7, value.stop_lon)
        size += ProtoAdapter.STRING.encodedSizeWithTag(8, value.zone_id)
        size += TranslatedString.ADAPTER.encodedSizeWithTag(9, value.stop_url)
        size += ProtoAdapter.STRING.encodedSizeWithTag(11, value.parent_station)
        size += ProtoAdapter.STRING.encodedSizeWithTag(12, value.stop_timezone)
        size += WheelchairBoarding.ADAPTER.encodedSizeWithTag(13, value.wheelchair_boarding)
        size += ProtoAdapter.STRING.encodedSizeWithTag(14, value.level_id)
        size += TranslatedString.ADAPTER.encodedSizeWithTag(15, value.platform_code)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Stop) {
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.stop_id)
        TranslatedString.ADAPTER.encodeWithTag(writer, 2, value.stop_code)
        TranslatedString.ADAPTER.encodeWithTag(writer, 3, value.stop_name)
        TranslatedString.ADAPTER.encodeWithTag(writer, 4, value.tts_stop_name)
        TranslatedString.ADAPTER.encodeWithTag(writer, 5, value.stop_desc)
        ProtoAdapter.FLOAT.encodeWithTag(writer, 6, value.stop_lat)
        ProtoAdapter.FLOAT.encodeWithTag(writer, 7, value.stop_lon)
        ProtoAdapter.STRING.encodeWithTag(writer, 8, value.zone_id)
        TranslatedString.ADAPTER.encodeWithTag(writer, 9, value.stop_url)
        ProtoAdapter.STRING.encodeWithTag(writer, 11, value.parent_station)
        ProtoAdapter.STRING.encodeWithTag(writer, 12, value.stop_timezone)
        WheelchairBoarding.ADAPTER.encodeWithTag(writer, 13, value.wheelchair_boarding)
        ProtoAdapter.STRING.encodeWithTag(writer, 14, value.level_id)
        TranslatedString.ADAPTER.encodeWithTag(writer, 15, value.platform_code)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Stop) {
        writer.writeBytes(value.unknownFields)
        TranslatedString.ADAPTER.encodeWithTag(writer, 15, value.platform_code)
        ProtoAdapter.STRING.encodeWithTag(writer, 14, value.level_id)
        WheelchairBoarding.ADAPTER.encodeWithTag(writer, 13, value.wheelchair_boarding)
        ProtoAdapter.STRING.encodeWithTag(writer, 12, value.stop_timezone)
        ProtoAdapter.STRING.encodeWithTag(writer, 11, value.parent_station)
        TranslatedString.ADAPTER.encodeWithTag(writer, 9, value.stop_url)
        ProtoAdapter.STRING.encodeWithTag(writer, 8, value.zone_id)
        ProtoAdapter.FLOAT.encodeWithTag(writer, 7, value.stop_lon)
        ProtoAdapter.FLOAT.encodeWithTag(writer, 6, value.stop_lat)
        TranslatedString.ADAPTER.encodeWithTag(writer, 5, value.stop_desc)
        TranslatedString.ADAPTER.encodeWithTag(writer, 4, value.tts_stop_name)
        TranslatedString.ADAPTER.encodeWithTag(writer, 3, value.stop_name)
        TranslatedString.ADAPTER.encodeWithTag(writer, 2, value.stop_code)
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.stop_id)
      }

      override fun decode(reader: ProtoReader): Stop {
        var stop_id: String? = null
        var stop_code: TranslatedString? = null
        var stop_name: TranslatedString? = null
        var tts_stop_name: TranslatedString? = null
        var stop_desc: TranslatedString? = null
        var stop_lat: Float? = null
        var stop_lon: Float? = null
        var zone_id: String? = null
        var stop_url: TranslatedString? = null
        var parent_station: String? = null
        var stop_timezone: String? = null
        var wheelchair_boarding: WheelchairBoarding? = null
        var level_id: String? = null
        var platform_code: TranslatedString? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> stop_id = ProtoAdapter.STRING.decode(reader)
            2 -> stop_code = TranslatedString.ADAPTER.decode(reader)
            3 -> stop_name = TranslatedString.ADAPTER.decode(reader)
            4 -> tts_stop_name = TranslatedString.ADAPTER.decode(reader)
            5 -> stop_desc = TranslatedString.ADAPTER.decode(reader)
            6 -> stop_lat = ProtoAdapter.FLOAT.decode(reader)
            7 -> stop_lon = ProtoAdapter.FLOAT.decode(reader)
            8 -> zone_id = ProtoAdapter.STRING.decode(reader)
            9 -> stop_url = TranslatedString.ADAPTER.decode(reader)
            11 -> parent_station = ProtoAdapter.STRING.decode(reader)
            12 -> stop_timezone = ProtoAdapter.STRING.decode(reader)
            13 -> try {
              wheelchair_boarding = WheelchairBoarding.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            14 -> level_id = ProtoAdapter.STRING.decode(reader)
            15 -> platform_code = TranslatedString.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Stop(
          stop_id = stop_id,
          stop_code = stop_code,
          stop_name = stop_name,
          tts_stop_name = tts_stop_name,
          stop_desc = stop_desc,
          stop_lat = stop_lat,
          stop_lon = stop_lon,
          zone_id = zone_id,
          stop_url = stop_url,
          parent_station = parent_station,
          stop_timezone = stop_timezone,
          wheelchair_boarding = wheelchair_boarding,
          level_id = level_id,
          platform_code = platform_code,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Stop): Stop = value.copy(
        stop_code = value.stop_code?.let(TranslatedString.ADAPTER::redact),
        stop_name = value.stop_name?.let(TranslatedString.ADAPTER::redact),
        tts_stop_name = value.tts_stop_name?.let(TranslatedString.ADAPTER::redact),
        stop_desc = value.stop_desc?.let(TranslatedString.ADAPTER::redact),
        stop_url = value.stop_url?.let(TranslatedString.ADAPTER::redact),
        platform_code = value.platform_code?.let(TranslatedString.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L

    @JvmSynthetic
    public inline fun build(body: Builder.() -> Unit): Stop = Builder().apply(body).build()
  }

  public enum class WheelchairBoarding(
    override val `value`: Int,
  ) : WireEnum {
    UNKNOWN(0),
    AVAILABLE(1),
    NOT_AVAILABLE(2),
    ;

    public companion object {
      @JvmField
      public val ADAPTER: ProtoAdapter<WheelchairBoarding> = object :
          EnumAdapter<WheelchairBoarding>(
        WheelchairBoarding::class, 
        PROTO_2, 
        WheelchairBoarding.UNKNOWN
      ) {
        override fun fromValue(`value`: Int): WheelchairBoarding? =
            WheelchairBoarding.fromValue(`value`)
      }

      @JvmStatic
      public fun fromValue(`value`: Int): WheelchairBoarding? = when (`value`) {
        0 -> UNKNOWN
        1 -> AVAILABLE
        2 -> NOT_AVAILABLE
        else -> null
      }
    }
  }
}
