// Code generated by Wire protocol buffer compiler, do not edit.
// Source: transit_realtime.Alert in xyz/ksharma/transport/gtfs_realtime.proto
@file:Suppress("DEPRECATION")

package xyz.ksharma.krail.network.model

import xyz.ksharma.krail.network.model.EntitySelector
import xyz.ksharma.krail.network.model.TimeRange
import xyz.ksharma.krail.network.model.TranslatedString
import com.squareup.wire.EnumAdapter
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_2
import com.squareup.wire.WireEnum
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.checkElementsNotNull
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlin.Suppress
import kotlin.Unit
import kotlin.collections.List
import okio.ByteString

public class Alert(
  active_period: List<TimeRange> = emptyList(),
  informed_entity: List<EntitySelector> = emptyList(),
  @field:WireField(
    tag = 6,
    adapter = "xyz.ksharma.krail.network.model.Alert${'$'}Cause#ADAPTER",
    schemaIndex = 2,
  )
  @JvmField
  public val cause: Cause? = null,
  @field:WireField(
    tag = 7,
    adapter = "xyz.ksharma.krail.network.model.Alert${'$'}Effect#ADAPTER",
    schemaIndex = 3,
  )
  @JvmField
  public val effect: Effect? = null,
  @field:WireField(
    tag = 8,
    adapter = "xyz.ksharma.krail.network.model.TranslatedString#ADAPTER",
    schemaIndex = 4,
  )
  @JvmField
  public val url: TranslatedString? = null,
  @field:WireField(
    tag = 10,
    adapter = "xyz.ksharma.krail.network.model.TranslatedString#ADAPTER",
    schemaIndex = 5,
  )
  @JvmField
  public val header_text: TranslatedString? = null,
  @field:WireField(
    tag = 11,
    adapter = "xyz.ksharma.krail.network.model.TranslatedString#ADAPTER",
    schemaIndex = 6,
  )
  @JvmField
  public val description_text: TranslatedString? = null,
  /**
   * NEW
   */
  @field:WireField(
    tag = 12,
    adapter = "xyz.ksharma.krail.network.model.TranslatedString#ADAPTER",
    schemaIndex = 7,
  )
  @JvmField
  public val tts_header_text: TranslatedString? = null,
  /**
   * NEW
   */
  @field:WireField(
    tag = 13,
    adapter = "xyz.ksharma.krail.network.model.TranslatedString#ADAPTER",
    schemaIndex = 8,
  )
  @JvmField
  public val tts_description_text: TranslatedString? = null,
  /**
   * NEW
   */
  @field:WireField(
    tag = 14,
    adapter = "xyz.ksharma.krail.network.model.Alert${'$'}SeverityLevel#ADAPTER",
    schemaIndex = 9,
  )
  @JvmField
  public val severity_level: SeverityLevel? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Alert, Alert.Builder>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "xyz.ksharma.krail.network.model.TimeRange#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 0,
  )
  @JvmField
  public val active_period: List<TimeRange> = immutableCopyOf("active_period", active_period)

  @field:WireField(
    tag = 5,
    adapter = "xyz.ksharma.krail.network.model.EntitySelector#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 1,
  )
  @JvmField
  public val informed_entity: List<EntitySelector> = immutableCopyOf("informed_entity",
      informed_entity)

  override fun newBuilder(): Builder {
    val builder = Builder()
    builder.active_period = active_period
    builder.informed_entity = informed_entity
    builder.cause = cause
    builder.effect = effect
    builder.url = url
    builder.header_text = header_text
    builder.description_text = description_text
    builder.tts_header_text = tts_header_text
    builder.tts_description_text = tts_description_text
    builder.severity_level = severity_level
    builder.addUnknownFields(unknownFields)
    return builder
  }

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Alert) return false
    if (unknownFields != other.unknownFields) return false
    if (active_period != other.active_period) return false
    if (informed_entity != other.informed_entity) return false
    if (cause != other.cause) return false
    if (effect != other.effect) return false
    if (url != other.url) return false
    if (header_text != other.header_text) return false
    if (description_text != other.description_text) return false
    if (tts_header_text != other.tts_header_text) return false
    if (tts_description_text != other.tts_description_text) return false
    if (severity_level != other.severity_level) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + active_period.hashCode()
      result = result * 37 + informed_entity.hashCode()
      result = result * 37 + (cause?.hashCode() ?: 0)
      result = result * 37 + (effect?.hashCode() ?: 0)
      result = result * 37 + (url?.hashCode() ?: 0)
      result = result * 37 + (header_text?.hashCode() ?: 0)
      result = result * 37 + (description_text?.hashCode() ?: 0)
      result = result * 37 + (tts_header_text?.hashCode() ?: 0)
      result = result * 37 + (tts_description_text?.hashCode() ?: 0)
      result = result * 37 + (severity_level?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (active_period.isNotEmpty()) result += """active_period=$active_period"""
    if (informed_entity.isNotEmpty()) result += """informed_entity=$informed_entity"""
    if (cause != null) result += """cause=$cause"""
    if (effect != null) result += """effect=$effect"""
    if (url != null) result += """url=$url"""
    if (header_text != null) result += """header_text=$header_text"""
    if (description_text != null) result += """description_text=$description_text"""
    if (tts_header_text != null) result += """tts_header_text=$tts_header_text"""
    if (tts_description_text != null) result += """tts_description_text=$tts_description_text"""
    if (severity_level != null) result += """severity_level=$severity_level"""
    return result.joinToString(prefix = "Alert{", separator = ", ", postfix = "}")
  }

  public fun copy(
    active_period: List<TimeRange> = this.active_period,
    informed_entity: List<EntitySelector> = this.informed_entity,
    cause: Cause? = this.cause,
    effect: Effect? = this.effect,
    url: TranslatedString? = this.url,
    header_text: TranslatedString? = this.header_text,
    description_text: TranslatedString? = this.description_text,
    tts_header_text: TranslatedString? = this.tts_header_text,
    tts_description_text: TranslatedString? = this.tts_description_text,
    severity_level: SeverityLevel? = this.severity_level,
    unknownFields: ByteString = this.unknownFields,
  ): Alert = Alert(active_period, informed_entity, cause, effect, url, header_text,
      description_text, tts_header_text, tts_description_text, severity_level, unknownFields)

  public class Builder : Message.Builder<Alert, Builder>() {
    @JvmField
    public var active_period: List<TimeRange> = emptyList()

    @JvmField
    public var informed_entity: List<EntitySelector> = emptyList()

    @JvmField
    public var cause: Cause? = null

    @JvmField
    public var effect: Effect? = null

    @JvmField
    public var url: TranslatedString? = null

    @JvmField
    public var header_text: TranslatedString? = null

    @JvmField
    public var description_text: TranslatedString? = null

    @JvmField
    public var tts_header_text: TranslatedString? = null

    @JvmField
    public var tts_description_text: TranslatedString? = null

    @JvmField
    public var severity_level: SeverityLevel? = null

    public fun active_period(active_period: List<TimeRange>): Builder {
      checkElementsNotNull(active_period)
      this.active_period = active_period
      return this
    }

    public fun informed_entity(informed_entity: List<EntitySelector>): Builder {
      checkElementsNotNull(informed_entity)
      this.informed_entity = informed_entity
      return this
    }

    public fun cause(cause: Cause?): Builder {
      this.cause = cause
      return this
    }

    public fun effect(effect: Effect?): Builder {
      this.effect = effect
      return this
    }

    public fun url(url: TranslatedString?): Builder {
      this.url = url
      return this
    }

    public fun header_text(header_text: TranslatedString?): Builder {
      this.header_text = header_text
      return this
    }

    public fun description_text(description_text: TranslatedString?): Builder {
      this.description_text = description_text
      return this
    }

    /**
     * NEW
     */
    public fun tts_header_text(tts_header_text: TranslatedString?): Builder {
      this.tts_header_text = tts_header_text
      return this
    }

    /**
     * NEW
     */
    public fun tts_description_text(tts_description_text: TranslatedString?): Builder {
      this.tts_description_text = tts_description_text
      return this
    }

    /**
     * NEW
     */
    public fun severity_level(severity_level: SeverityLevel?): Builder {
      this.severity_level = severity_level
      return this
    }

    override fun build(): Alert = Alert(
      active_period = active_period,
      informed_entity = informed_entity,
      cause = cause,
      effect = effect,
      url = url,
      header_text = header_text,
      description_text = description_text,
      tts_header_text = tts_header_text,
      tts_description_text = tts_description_text,
      severity_level = severity_level,
      unknownFields = buildUnknownFields()
    )
  }

  public companion object {
    @JvmField
    public val DEFAULT_CAUSE: Cause = Cause.UNKNOWN_CAUSE

    @JvmField
    public val DEFAULT_EFFECT: Effect = Effect.UNKNOWN_EFFECT

    @JvmField
    public val ADAPTER: ProtoAdapter<Alert> = object : ProtoAdapter<Alert>(
      FieldEncoding.LENGTH_DELIMITED, 
      Alert::class, 
      "type.googleapis.com/transit_realtime.Alert", 
      PROTO_2, 
      null, 
      "xyz/ksharma/transport/gtfs_realtime.proto"
    ) {
      override fun encodedSize(`value`: Alert): Int {
        var size = value.unknownFields.size
        size += TimeRange.ADAPTER.asRepeated().encodedSizeWithTag(1, value.active_period)
        size += EntitySelector.ADAPTER.asRepeated().encodedSizeWithTag(5, value.informed_entity)
        size += Cause.ADAPTER.encodedSizeWithTag(6, value.cause)
        size += Effect.ADAPTER.encodedSizeWithTag(7, value.effect)
        size += TranslatedString.ADAPTER.encodedSizeWithTag(8, value.url)
        size += TranslatedString.ADAPTER.encodedSizeWithTag(10, value.header_text)
        size += TranslatedString.ADAPTER.encodedSizeWithTag(11, value.description_text)
        size += TranslatedString.ADAPTER.encodedSizeWithTag(12, value.tts_header_text)
        size += TranslatedString.ADAPTER.encodedSizeWithTag(13, value.tts_description_text)
        size += SeverityLevel.ADAPTER.encodedSizeWithTag(14, value.severity_level)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Alert) {
        TimeRange.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.active_period)
        EntitySelector.ADAPTER.asRepeated().encodeWithTag(writer, 5, value.informed_entity)
        Cause.ADAPTER.encodeWithTag(writer, 6, value.cause)
        Effect.ADAPTER.encodeWithTag(writer, 7, value.effect)
        TranslatedString.ADAPTER.encodeWithTag(writer, 8, value.url)
        TranslatedString.ADAPTER.encodeWithTag(writer, 10, value.header_text)
        TranslatedString.ADAPTER.encodeWithTag(writer, 11, value.description_text)
        TranslatedString.ADAPTER.encodeWithTag(writer, 12, value.tts_header_text)
        TranslatedString.ADAPTER.encodeWithTag(writer, 13, value.tts_description_text)
        SeverityLevel.ADAPTER.encodeWithTag(writer, 14, value.severity_level)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Alert) {
        writer.writeBytes(value.unknownFields)
        SeverityLevel.ADAPTER.encodeWithTag(writer, 14, value.severity_level)
        TranslatedString.ADAPTER.encodeWithTag(writer, 13, value.tts_description_text)
        TranslatedString.ADAPTER.encodeWithTag(writer, 12, value.tts_header_text)
        TranslatedString.ADAPTER.encodeWithTag(writer, 11, value.description_text)
        TranslatedString.ADAPTER.encodeWithTag(writer, 10, value.header_text)
        TranslatedString.ADAPTER.encodeWithTag(writer, 8, value.url)
        Effect.ADAPTER.encodeWithTag(writer, 7, value.effect)
        Cause.ADAPTER.encodeWithTag(writer, 6, value.cause)
        EntitySelector.ADAPTER.asRepeated().encodeWithTag(writer, 5, value.informed_entity)
        TimeRange.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.active_period)
      }

      override fun decode(reader: ProtoReader): Alert {
        val active_period = mutableListOf<TimeRange>()
        val informed_entity = mutableListOf<EntitySelector>()
        var cause: Cause? = null
        var effect: Effect? = null
        var url: TranslatedString? = null
        var header_text: TranslatedString? = null
        var description_text: TranslatedString? = null
        var tts_header_text: TranslatedString? = null
        var tts_description_text: TranslatedString? = null
        var severity_level: SeverityLevel? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> active_period.add(TimeRange.ADAPTER.decode(reader))
            5 -> informed_entity.add(EntitySelector.ADAPTER.decode(reader))
            6 -> try {
              cause = Cause.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            7 -> try {
              effect = Effect.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            8 -> url = TranslatedString.ADAPTER.decode(reader)
            10 -> header_text = TranslatedString.ADAPTER.decode(reader)
            11 -> description_text = TranslatedString.ADAPTER.decode(reader)
            12 -> tts_header_text = TranslatedString.ADAPTER.decode(reader)
            13 -> tts_description_text = TranslatedString.ADAPTER.decode(reader)
            14 -> try {
              severity_level = SeverityLevel.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            else -> reader.readUnknownField(tag)
          }
        }
        return Alert(
          active_period = active_period,
          informed_entity = informed_entity,
          cause = cause,
          effect = effect,
          url = url,
          header_text = header_text,
          description_text = description_text,
          tts_header_text = tts_header_text,
          tts_description_text = tts_description_text,
          severity_level = severity_level,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Alert): Alert = value.copy(
        active_period = value.active_period.redactElements(TimeRange.ADAPTER),
        informed_entity = value.informed_entity.redactElements(EntitySelector.ADAPTER),
        url = value.url?.let(TranslatedString.ADAPTER::redact),
        header_text = value.header_text?.let(TranslatedString.ADAPTER::redact),
        description_text = value.description_text?.let(TranslatedString.ADAPTER::redact),
        tts_header_text = value.tts_header_text?.let(TranslatedString.ADAPTER::redact),
        tts_description_text = value.tts_description_text?.let(TranslatedString.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L

    @JvmSynthetic
    public inline fun build(body: Builder.() -> Unit): Alert = Builder().apply(body).build()
  }

  public enum class Cause(
    override val `value`: Int,
  ) : WireEnum {
    UNKNOWN_CAUSE(1),
    /**
     * NEW
     */
    OTHER_CAUSE(2),
    TECHNICAL_PROBLEM(3),
    /**
     * NEW
     */
    STRIKE(4),
    /**
     * NEW
     */
    DEMONSTRATION(5),
    ACCIDENT(6),
    HOLIDAY(7),
    WEATHER(8),
    MAINTENANCE(9),
    CONSTRUCTION(10),
    POLICE_ACTIVITY(11),
    MEDICAL_EMERGENCY(12),
    ;

    public companion object {
      @JvmField
      public val ADAPTER: ProtoAdapter<Cause> = object : EnumAdapter<Cause>(
        Cause::class, 
        PROTO_2, 
        null
      ) {
        override fun fromValue(`value`: Int): Cause? = Companion.fromValue(`value`)
      }

      @JvmStatic
      public fun fromValue(`value`: Int): Cause? = when (`value`) {
        1 -> UNKNOWN_CAUSE
        2 -> OTHER_CAUSE
        3 -> TECHNICAL_PROBLEM
        4 -> STRIKE
        5 -> DEMONSTRATION
        6 -> ACCIDENT
        7 -> HOLIDAY
        8 -> WEATHER
        9 -> MAINTENANCE
        10 -> CONSTRUCTION
        11 -> POLICE_ACTIVITY
        12 -> MEDICAL_EMERGENCY
        else -> null
      }
    }
  }

  public enum class Effect(
    override val `value`: Int,
  ) : WireEnum {
    NO_SERVICE(1),
    REDUCED_SERVICE(2),
    SIGNIFICANT_DELAYS(3),
    DETOUR(4),
    ADDITIONAL_SERVICE(5),
    MODIFIED_SERVICE(6),
    OTHER_EFFECT(7),
    UNKNOWN_EFFECT(8),
    STOP_MOVED(9),
    /**
     * NEW
     */
    NO_EFFECT(10),
    /**
     * NEW
     */
    ACCESSIBILITY_ISSUE(11),
    ;

    public companion object {
      @JvmField
      public val ADAPTER: ProtoAdapter<Effect> = object : EnumAdapter<Effect>(
        Effect::class, 
        PROTO_2, 
        null
      ) {
        override fun fromValue(`value`: Int): Effect? = Companion.fromValue(`value`)
      }

      @JvmStatic
      public fun fromValue(`value`: Int): Effect? = when (`value`) {
        1 -> NO_SERVICE
        2 -> REDUCED_SERVICE
        3 -> SIGNIFICANT_DELAYS
        4 -> DETOUR
        5 -> ADDITIONAL_SERVICE
        6 -> MODIFIED_SERVICE
        7 -> OTHER_EFFECT
        8 -> UNKNOWN_EFFECT
        9 -> STOP_MOVED
        10 -> NO_EFFECT
        11 -> ACCESSIBILITY_ISSUE
        else -> null
      }
    }
  }

  public enum class SeverityLevel(
    override val `value`: Int,
  ) : WireEnum {
    /**
     * NEW
     */
    UNKNOWN_SEVERITY(1),
    INFO(2),
    WARNING(3),
    SEVERE(4),
    ;

    public companion object {
      @JvmField
      public val ADAPTER: ProtoAdapter<SeverityLevel> = object : EnumAdapter<SeverityLevel>(
        SeverityLevel::class, 
        PROTO_2, 
        null
      ) {
        override fun fromValue(`value`: Int): SeverityLevel? = Companion.fromValue(`value`)
      }

      @JvmStatic
      public fun fromValue(`value`: Int): SeverityLevel? = when (`value`) {
        1 -> UNKNOWN_SEVERITY
        2 -> INFO
        3 -> WARNING
        4 -> SEVERE
        else -> null
      }
    }
  }
}
