// Code generated by Wire protocol buffer compiler, do not edit.
// Source: transit_realtime.TfnswVehicleDescriptor in xyz/ksharma/transport/gtfs_realtime.proto
@file:Suppress("DEPRECATION")

package xyz.ksharma.krail.network.model

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_2
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmSynthetic
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlin.Suppress
import kotlin.Unit
import okio.ByteString

/**
 * NEW
 */
public class TfnswVehicleDescriptor(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    schemaIndex = 0,
  )
  @JvmField
  public val air_conditioned: Boolean? = null,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    schemaIndex = 1,
  )
  @JvmField
  public val wheelchair_accessible: Int? = null,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 2,
  )
  @JvmField
  public val vehicle_model: String? = null,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    schemaIndex = 3,
  )
  @JvmField
  public val performing_prior_trip: Boolean? = null,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    schemaIndex = 4,
  )
  @JvmField
  public val special_vehicle_attributes: Int? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<TfnswVehicleDescriptor, TfnswVehicleDescriptor.Builder>(ADAPTER, unknownFields) {
  override fun newBuilder(): Builder {
    val builder = Builder()
    builder.air_conditioned = air_conditioned
    builder.wheelchair_accessible = wheelchair_accessible
    builder.vehicle_model = vehicle_model
    builder.performing_prior_trip = performing_prior_trip
    builder.special_vehicle_attributes = special_vehicle_attributes
    builder.addUnknownFields(unknownFields)
    return builder
  }

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is TfnswVehicleDescriptor) return false
    if (unknownFields != other.unknownFields) return false
    if (air_conditioned != other.air_conditioned) return false
    if (wheelchair_accessible != other.wheelchair_accessible) return false
    if (vehicle_model != other.vehicle_model) return false
    if (performing_prior_trip != other.performing_prior_trip) return false
    if (special_vehicle_attributes != other.special_vehicle_attributes) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (air_conditioned?.hashCode() ?: 0)
      result = result * 37 + (wheelchair_accessible?.hashCode() ?: 0)
      result = result * 37 + (vehicle_model?.hashCode() ?: 0)
      result = result * 37 + (performing_prior_trip?.hashCode() ?: 0)
      result = result * 37 + (special_vehicle_attributes?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (air_conditioned != null) result += """air_conditioned=$air_conditioned"""
    if (wheelchair_accessible != null) result += """wheelchair_accessible=$wheelchair_accessible"""
    if (vehicle_model != null) result += """vehicle_model=${sanitize(vehicle_model)}"""
    if (performing_prior_trip != null) result += """performing_prior_trip=$performing_prior_trip"""
    if (special_vehicle_attributes != null) result +=
        """special_vehicle_attributes=$special_vehicle_attributes"""
    return result.joinToString(prefix = "TfnswVehicleDescriptor{", separator = ", ", postfix = "}")
  }

  public fun copy(
    air_conditioned: Boolean? = this.air_conditioned,
    wheelchair_accessible: Int? = this.wheelchair_accessible,
    vehicle_model: String? = this.vehicle_model,
    performing_prior_trip: Boolean? = this.performing_prior_trip,
    special_vehicle_attributes: Int? = this.special_vehicle_attributes,
    unknownFields: ByteString = this.unknownFields,
  ): TfnswVehicleDescriptor = TfnswVehicleDescriptor(air_conditioned, wheelchair_accessible,
      vehicle_model, performing_prior_trip, special_vehicle_attributes, unknownFields)

  public class Builder : Message.Builder<TfnswVehicleDescriptor, Builder>() {
    @JvmField
    public var air_conditioned: Boolean? = null

    @JvmField
    public var wheelchair_accessible: Int? = null

    @JvmField
    public var vehicle_model: String? = null

    @JvmField
    public var performing_prior_trip: Boolean? = null

    @JvmField
    public var special_vehicle_attributes: Int? = null

    public fun air_conditioned(air_conditioned: Boolean?): Builder {
      this.air_conditioned = air_conditioned
      return this
    }

    public fun wheelchair_accessible(wheelchair_accessible: Int?): Builder {
      this.wheelchair_accessible = wheelchair_accessible
      return this
    }

    public fun vehicle_model(vehicle_model: String?): Builder {
      this.vehicle_model = vehicle_model
      return this
    }

    public fun performing_prior_trip(performing_prior_trip: Boolean?): Builder {
      this.performing_prior_trip = performing_prior_trip
      return this
    }

    public fun special_vehicle_attributes(special_vehicle_attributes: Int?): Builder {
      this.special_vehicle_attributes = special_vehicle_attributes
      return this
    }

    override fun build(): TfnswVehicleDescriptor = TfnswVehicleDescriptor(
      air_conditioned = air_conditioned,
      wheelchair_accessible = wheelchair_accessible,
      vehicle_model = vehicle_model,
      performing_prior_trip = performing_prior_trip,
      special_vehicle_attributes = special_vehicle_attributes,
      unknownFields = buildUnknownFields()
    )
  }

  public companion object {
    public const val DEFAULT_AIR_CONDITIONED: Boolean = false

    public const val DEFAULT_WHEELCHAIR_ACCESSIBLE: Int = 0

    public const val DEFAULT_PERFORMING_PRIOR_TRIP: Boolean = false

    public const val DEFAULT_SPECIAL_VEHICLE_ATTRIBUTES: Int = 0

    @JvmField
    public val ADAPTER: ProtoAdapter<TfnswVehicleDescriptor> = object :
        ProtoAdapter<TfnswVehicleDescriptor>(
      FieldEncoding.LENGTH_DELIMITED, 
      TfnswVehicleDescriptor::class, 
      "type.googleapis.com/transit_realtime.TfnswVehicleDescriptor", 
      PROTO_2, 
      null, 
      "xyz/ksharma/transport/gtfs_realtime.proto"
    ) {
      override fun encodedSize(`value`: TfnswVehicleDescriptor): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.BOOL.encodedSizeWithTag(1, value.air_conditioned)
        size += ProtoAdapter.INT32.encodedSizeWithTag(2, value.wheelchair_accessible)
        size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.vehicle_model)
        size += ProtoAdapter.BOOL.encodedSizeWithTag(4, value.performing_prior_trip)
        size += ProtoAdapter.INT32.encodedSizeWithTag(5, value.special_vehicle_attributes)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: TfnswVehicleDescriptor) {
        ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.air_conditioned)
        ProtoAdapter.INT32.encodeWithTag(writer, 2, value.wheelchair_accessible)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.vehicle_model)
        ProtoAdapter.BOOL.encodeWithTag(writer, 4, value.performing_prior_trip)
        ProtoAdapter.INT32.encodeWithTag(writer, 5, value.special_vehicle_attributes)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: TfnswVehicleDescriptor) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.INT32.encodeWithTag(writer, 5, value.special_vehicle_attributes)
        ProtoAdapter.BOOL.encodeWithTag(writer, 4, value.performing_prior_trip)
        ProtoAdapter.STRING.encodeWithTag(writer, 3, value.vehicle_model)
        ProtoAdapter.INT32.encodeWithTag(writer, 2, value.wheelchair_accessible)
        ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.air_conditioned)
      }

      override fun decode(reader: ProtoReader): TfnswVehicleDescriptor {
        var air_conditioned: Boolean? = null
        var wheelchair_accessible: Int? = null
        var vehicle_model: String? = null
        var performing_prior_trip: Boolean? = null
        var special_vehicle_attributes: Int? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> air_conditioned = ProtoAdapter.BOOL.decode(reader)
            2 -> wheelchair_accessible = ProtoAdapter.INT32.decode(reader)
            3 -> vehicle_model = ProtoAdapter.STRING.decode(reader)
            4 -> performing_prior_trip = ProtoAdapter.BOOL.decode(reader)
            5 -> special_vehicle_attributes = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return TfnswVehicleDescriptor(
          air_conditioned = air_conditioned,
          wheelchair_accessible = wheelchair_accessible,
          vehicle_model = vehicle_model,
          performing_prior_trip = performing_prior_trip,
          special_vehicle_attributes = special_vehicle_attributes,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: TfnswVehicleDescriptor): TfnswVehicleDescriptor = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L

    @JvmSynthetic
    public inline fun build(body: Builder.() -> Unit): TfnswVehicleDescriptor =
        Builder().apply(body).build()
  }
}
