// Code generated by Wire protocol buffer compiler, do not edit.
// Source: transit_realtime.TrackDirection in xyz/ksharma/transport/gtfs_realtime.proto
@file:Suppress("DEPRECATION")

package xyz.ksharma.krail.network.model

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_2
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * / --- TfNSW Extensions
 */
public enum class TrackDirection(
  override val `value`: Int,
) : WireEnum {
  UP(0),
  DOWN(1),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<TrackDirection> = object : EnumAdapter<TrackDirection>(
      TrackDirection::class, 
      PROTO_2, 
      TrackDirection.UP
    ) {
      override fun fromValue(`value`: Int): TrackDirection? = TrackDirection.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): TrackDirection? = when (`value`) {
      0 -> UP
      1 -> DOWN
      else -> null
    }
  }
}
