name: Krail App CI

on:
  push:
    branches: [ main, prod/* ]
  pull_request:
    branches: [ main, prod/* ]
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-android-debug:
    uses: ./.github/workflows/build-android.yml
    with:
      variant: debug
    secrets: inherit

  build-android-release:
    uses: ./.github/workflows/build-android.yml
    with:
      variant: release
    secrets: inherit

  build-ios:
    uses: ./.github/workflows/build-ios.yml
    secrets: inherit