name: Krail App CI

on:
  push:
    branches: [ main, prod/* ]
  pull_request:
    branches: [ main, prod/* ]
    types: [ opened, synchronize, reopened, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-android-debug:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    uses: ./.github/workflows/build-android.yml
    with:
      variant: debug
    secrets: inherit

  build-android-release:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    uses: ./.github/workflows/build-android.yml
    with:
      variant: release
    secrets: inherit

  build-ios:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    uses: ./.github/workflows/build-ios.yml
    secrets: inherit

  distribute-debug-apk-firebase:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build-android-debug
    uses: ./.github/workflows/distribute-firebase.yml
    with:
      variant: debug
    secrets: inherit

  distribute-release-apk-firebase:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build-android-release
    uses: ./.github/workflows/distribute-firebase.yml
    with:
      variant: release
    secrets: inherit

  distribute-google-play:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/prod/')
    needs: build-android-release
    uses: ./.github/workflows/distribute-google-play.yml
    with:
      artifact-name: composeApp-release-aab-${{ github.run_id }}
    secrets: inherit

  create-github-release:
    # Only create a release for prod branch pushes
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/prod/')
    needs: distribute-google-play
    uses: ./.github/workflows/create-github-release.yml
    with:
      tag_name: v${{ needs.android.outputs.version_name }}
    secrets: inherit
