name: Krail App CI

on:
  push:
    branches: [ main, prod/* ]
  pull_request:
    branches: [ main, prod/* ]
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-android-debug:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    uses: ./.github/workflows/build-android.yml
    with:
      variant: debug
    secrets: inherit

  build-android-release:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    uses: ./.github/workflows/build-android.yml
    with:
      variant: release
    secrets: inherit

  build-ios:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    uses: ./.github/workflows/build-ios.yml
    secrets: inherit

  distribute-debug-apk:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build-android-debug
    uses: ./.github/workflows/firebase-app-distribution.yml
    with:
      variant: debug
    secrets: inherit

  distribute-release-apk:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build-android-release
    uses: ./.github/workflows/firebase-app-distribution.yml
    with:
      variant: release
    secrets: inherit
