name: Firebase App Distribution

on:
  workflow_dispatch:
    inputs:
      should_distribute:
        description: 'Whether to distribute the app (true/false)'
        required: true
        type: boolean
  pull_request:
    branches:
      - debug-alpha

jobs:
  distribute:
    runs-on: ubuntu-latest
    needs: setup-gradle # Add the setup-gradle job as a dependency
    if: ${{ github.event.inputs.should_distribute }} # Run only if should_distribute is true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup_gradle.yml@main # Call reusable workflow

      - name: Firebase (Debug) - Google Services.json file
        env:
          DATA: ${{ secrets.FIREBASE_GOOGLE_SERVICES_JSON_DEBUG }}
        run: echo $DATA | base64 -di > app/src/debug/google-services.json

      - name: Build APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: |
          firebase appdistribution:distribute app/build/outputs/apk/debug/app-debug.apk \
            --app ${{ secrets.FIREBASE_APP_ID_DEBUG }} \
            --groups "Friends" \
            --release-notes "Automated release"
