name: Google Play Release

on:
  push:
    branches:
      - 'prod/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-android-release:
    if: ${{ github.event.pull_request.draft == false }}
    uses: ./.github/workflows/build-android.yml
    with:
      variant: release
    secrets: inherit

  distribute-google-play:
    needs: android
    runs-on: ubuntu-latest
    environment: Firebase
    steps:
      - name: Download Release AAB artifact
        uses: actions/download-artifact@v4
        with:
          name: composeApp-release-aab-${{ github.run_id }}
          path: aab

      - name: Deploy to Play Store (Internal)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: xyz.ksharma.krail
          releaseFiles: aab/*.aab
          track: internal

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_KRAIL_GITHUB }}
        with:
          tag_name: v${{ needs.android.outputs.version_name }}
          generate_release_notes: true
          draft: true
